@host = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoidGVzdGVyNCIsImlhdCI6MTc1ODk2NjMzMywiZXhwIjoxNzU5NTcxMTMzfQ.IqgfqFFFpUJuQK1ewNJNeVFaF4bYEn4ev9JP5aZl-rM
@exerciseId = 6

### Create
POST {{host}}/api/fitness/exercises/{{exerciseId}}/instructions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "instructions": "Maintain a neutral spine and drive through your heels."
}

### Get
GET {{host}}/api/fitness/exercises/{{exerciseId}}/instructions
Authorization: Bearer {{token}}

### Update
PUT {{host}}/api/fitness/exercises/{{exerciseId}}/instructions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "instructions": "Brace, ribs down, control the eccentric."
}

### Delete
DELETE {{host}}/api/fitness/exercises/{{exerciseId}}/instructions
Authorization: Bearer {{token}}
